--CREATE TABLES
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    EMPLOYEE_FIRSTNAME VARCHAR2(100),
    EMPLOYEE_LASTNAME VARCHAR2(100),
    DEPARTMENT_ID INTEGER,
    SALARY NUMBER,
    EMAIL VARCHAR(100)
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INTEGER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100)
);

--CREATE SEQUENCE AND TRIGGER TO GENERATE PRIMARY KEY VALUES
CREATE SEQUENCE EMP_ID_PK
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE DEPT_ID_PK
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER INSERT_EMP_ID
BEFORE INSERT ON EMPLOYEE_ID
FOR EACH ROW
BEGIN
    SELECT EMP_ID_PK INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER INSERT_DEPT_ID
BEFORE INSERT ON EMPLOYEE_ID
FOR EACH ROW
BEGIN
    SELECT DEPT_ID_PK INTO :NEW.DEPTARTMENT_ID FROM DUAL;
END;