DROP TABLE REIMBURSEMENTS;
DROP TABLE EMPLOYEE;
DROP TABLE MANAGER;

CREATE TABLE MANAGER (
    MANAGER_FIRSTNAME VARCHAR2(100),
    MANAGER_LASTNAME VARCHAR2(100),
    MANAGER_ID INTEGER PRIMARY KEY,
    MANAGER_PASSWORD VARCHAR2(100)
);
/
CREATE TABLE EMPLOYEE (
    EMPLOYEE_FIRSTNAME VARCHAR2(100),
    EMPLOYEE_LASTNAME VARCHAR(100),
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    EMPLOYEE_PASSWORD VARCHAR2(100),
    MANAGER_ID INTEGER,
    FOREIGN KEY(MANAGER_ID) REFERENCES MANAGER(MANAGER_ID)
);
/
CREATE TABLE REIMBURSEMENTS (
    REIMBURSEMENT_ID INTEGER PRIMARY KEY,
    AMOUNT NUMBER,
    GOES_TO INTEGER,
    FOREIGN KEY(GOES_TO) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);
/
INSERT INTO MANAGER
VALUES('Big', 'Boss', 1, 'something');

INSERT INTO EMPLOYEE
VALUES ('Zach', 'Macaulay', 1, 'password', 1);

INSERT INTO EMPLOYEE
VALUES('Some', 'OneElse', 2, 'wordpass', 1);